export enum UserRoleEnum {
  ROLE_MANAGER = 'ROLE_MANAGER',
  LIST_USERS = 'LIST_USERS',
  NEWS_MANAGER = 'NEWS_MANAGER',
  MEDIA_MANAGER = 'MEDIA_MANAGER',
  SIM_DATA_MANAGER = 'SIM_DATA_MANAGER',
  ORDER_MANAGER = 'ORDER_MANAGER',
  PAYMENT_VIEW = 'PAYMENT_VIEW',
  PAYMENT_ADD = 'PAYMENT_ADD',
  VNMB_SETUP = 'VNMB_SETUP',
}
